version: '3.8'

services:
  db:
    container_name: linkedin-container
    image: postgres:latest
    environment:
      POSTGRES_USER: accomplish
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/accomplish
    ports:
      - "5454:5432"
    networks:
      - db
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
